install:
  - curl -L "http://nusmv.fbk.eu/distrib/NuSMV-2.6.0-zchaff-linux64.tar.gz" | tar --extract --gzip --strip-components=2 "NuSMV-2.6.0-Linux/bin/NuSMV"

script:
  - ./NuSMV -v 3 river.smv
  - ./NuSMV -bmc -v 3 queens.smv
