install:
  - curl -L "http://nusmv.fbk.eu/distrib/NuSMV-2.6.0-zchaff-linux64.tar.gz" | tar --verbose --extract --gzip --strip-components=2 -C $HOME/bin "NuSMV-2.6.0-Linux/bin/NuSMV" 

script:
  - ./river.py ltl
  - ./river.py ctl
  - ./queens.py ltl
  - ./queens.py ctl
